### PR TITLE
Add bifrost decorator

### PR DESCRIPTION
**Pull request by Akagi201**
Add support for [Bifrost](https://github.com/bifrost-finance/bifrost)

### CODE REVIEW

**Comment by pepoviola** [comment]
Hi @Akagi201, looks good thanks!! I will add the a test to run in our `ci`. Is this the official image `https://hub.docker.com/r/bifrostnetwork/bifrost`? 
Thanks!

**Review by pepoviola — APPROVED** [review]

**Comment by wirednkod** [comment]
@Akagi201 Is there a specific reason why there is package dependency upgrades in this PR?

**Comment by Akagi201** [comment]
@wirednkod It's not needed,I can remove them.

**Review by wirednkod — APPROVED** [review]

**Comment by Akagi201** [comment]
@pepoviola Yes, it's our official docker image. And if you have any error in the CI, you may ping me.

**Review by pepoviola — APPROVED** [review]

**Comment by pepoviola** [comment]
Looks good, thanks @Akagi201!! 🙌

**Pull request merged**
