### PR TITLE
Base path for relay chain part

### PR DESCRIPTION
**Pull request by MucTepDayH16**
While testing zombienet with local chain I've encountered DB lock error. If I was running parachains with two nodes, collators stores their DB in temporary location but relay parts of parachain don't: it is stored in general localtion on my computer and lead to DB lock.

So, this PR solved this error for me and also could be useful for anyone using `zombienet`

### CODE REVIEW

**Comment by pepoviola** [comment]
Hi @MucTepDayH16, sorry about the delay and thanks for your contribution!! Can you resolve the conflicts so I can merge this one. Thanks!!

**Review by pepoviola — APPROVED** [review]
Looks good, need to resolve an small conflict before merge 👍

**Comment by MucTepDayH16** [comment]
> Looks good, need to resolve an small conflict before merge 👍

Sure

**Comment by MucTepDayH16** [comment]
Hi @pepoviola, is `continuous-integration/gitlab-paras ` blocking merge

**Comment by pepoviola** [comment]
> Hi @pepoviola, is `continuous-integration/gitlab-paras ` blocking merge

Hi @MucTepDayH16, we should add the same fix for other providers. Now is failing because `/relay-data` doesn't have access in `k8s`

```
Error: Service(Keystore(Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })))
```

I will add the fix for podman/k8s in another pr 👍

**Comment by pepoviola** [comment]
ping @MucTepDayH16, can you change the base branch of this pr to this one `add-volume-relay-collator` since there is the fix for `podman/k8s`.

Thanks!

**Comment by MucTepDayH16** [comment]
@pepoviola can you reopen this PR. You deleted `add-volume-relay-collator` and my changes had lost

**Comment by pepoviola** [comment]
Sorry @MucTepDayH16, yes. That branch is already merged. You can open agains `main` and should works now.
Thanks!!! and sorry again about the changes.

**Pull request closed without merging**
