### PR TITLE
Use grafana teleport URL

### PR DESCRIPTION
**Pull request by skunert**
Closes https://github.com/paritytech/zombienet/issues/1584

Allows usage of grafana logs without vpn.

### CODE REVIEW

**Comment by pepoviola** [comment]
Awesome, thanks for your contribution @skunert 🙌

**Review by wirednkod — APPROVED** [review]

**Comment by pepoviola** [comment]
I'm not sure why the `nix hash update` check fails since this pr doesn't touch any dep. Could be that the nix config is not reading from the `lock` file?

**Comment by wirednkod** [comment]
> I'm not sure why the `nix hash update` check fails since this pr doesn't touch any dep. Could be that the nix config is not reading from the `lock` file?

https://github.com/paritytech/zombienet/actions/runs/7102648724/job/19333502741?pr=1586

**Comment by wirednkod** [comment]
> > > I'm not sure why the `nix hash update` check fails since this pr doesn't touch any dep. Could be that the nix config is not reading from the `lock` file?
> > 
> > 
> > [paritytech/zombienet/actions/runs/7102648724/job/19333502741?pr=1586](https://github.com/paritytech/zombienet/actions/runs/7102648724/job/19333502741?pr=1586)
> 
> Thanks @wirednkod, I merged :) But I want to understand how to automate this. I think could be because the `orchestrator` is itself a dep of the `cli` but I'm not sure. I will try to check how this works internally. Thx!

Based on a comment, this hash changes with any update of the dependencies, but it is not automatically updated from SRI of package.lock

**Comment by pepoviola** [comment]
> > > > I'm not sure why the `nix hash update` check fails since this pr doesn't touch any dep. Could be that the nix config is not reading from the `lock` file?
> > > 
> > > 
> > > [paritytech/zombienet/actions/runs/7102648724/job/19333502741?pr=1586](https://github.com/paritytech/zombienet/actions/runs/7102648724/job/19333502741?pr=1586)
> > 
> > 
> > Thanks @wirednkod, I merged :) But I want to understand how to automate this. I think could be because the `orchestrator` is itself a dep of the `cli` but I'm not sure. I will try to check how this works internally. Thx!
> 
> Based on a comment, this hash changes with any update of the dependencies, but it is not automatically updated from SRI of package.lock

Yes, and as we are using the `orchestrator` as dep of `cli`  I think any change needs to update the hash. We should automate this in a way that is easy to do it locally.
Thx!

**Pull request merged**
