### PR TITLE
remove shell redirection for cumulus based collators

### LINKED ISSUE #1520: Adjust export commands to work with cumulus/non-cumulus collators
Take this pr as base https://github.com/paritytech/zombienet/pull/1515.

cc: @JoshOrndorff

### PR DESCRIPTION
**Pull request by pepoviola**
Based on https://github.com/paritytech/zombienet/pull/1515, fix #1520 
*NOTE*: we should remove the conditional in the near future.

Also, @wirednkod we should review other places where we are using shell redirections.

cc: @JoshOrndorff

### CODE REVIEW

**Comment by wirednkod** [comment]
As pointed out [here](https://github.com/paritytech/zombienet/pull/1515#issuecomment-1811968348) there are some redirections that need to be added. Should we try to push those in 1 commit?

**Comment by pepoviola** [comment]
> As pointed out [here](https://github.com/paritytech/zombienet/pull/1515#issuecomment-1811968348) there are some redirections that need to be added. Should we try to push those in 1 commit?

I think is better to handle those in a follow up pr, did you want to work on that @wirednkod ?

**Comment by wirednkod** [comment]
Sure thing @pepoviola

**Comment by pepoviola** [comment]
Thanks!!

**Review by wirednkod — APPROVED** [review]

**Pull request merged**
