### PR TITLE
Updated docs/book files with new mdbook version

### PR DESCRIPTION
**Pull request by Neyromancer**
## Descritption

Update docs/book HTML files with new version of mdbook.
mdbook v0.4.35

Relates to [PR #1439](https://github.com/paritytech/zombienet/pull/1439) and [issue #1412](https://github.com/paritytech/zombienet/issues/1412)

This PR should be as a preparation for [PR #1439](https://github.com/paritytech/zombienet/pull/1439) which make changes to doc files.

### CODE REVIEW

**Comment by pepoviola** [comment]
Thanks for your contribution @Neyromancer! but let me ping @wirednkod to correct me if I'm wrong, but I think the `html` files of `docs/book` are auto-generated by a workflow in GHA. We should no manually change those, if need to update the mdBook version we should update the [workflow](https://github.com/paritytech/zombienet/blob/main/.github/workflows/gh-pages.yml)
Thx!

**Comment by Neyromancer** [comment]
> Thanks for your contribution @Neyromancer! but let me ping @wirednkod to correct me if I'm wrong, but I think the `html` files of `docs/book` are auto-generated by a workflow in GHA. We should no manually change those, if need to update the mdBook version we should update the [workflow](https://github.com/paritytech/zombienet/blob/main/.github/workflows/gh-pages.yml) Thx!

Looks as if it is indeed should be updated there. Did not check CI scripts, pardon

**Comment by wirednkod** [comment]
> Thanks for your contribution @Neyromancer! but let me ping @wirednkod to correct me if I'm wrong, but I think the `html` files of `docs/book` are auto-generated by a workflow in GHA. We should no manually change those, if need to update the mdBook version we should update the [workflow](https://github.com/paritytech/zombienet/blob/main/.github/workflows/gh-pages.yml?rgh-link-date=2023-11-09T22%3A51%3A04Z) Thx!

That is correct. The changed files will though be overwritten and since same changes applied everywhere then, the final doc files will be correct

**Comment by wirednkod** [comment]
Closing this as it does not make sense to update the files that willbe overridden

**Comment by pepoviola** [comment]
Hi @Neyromancer thanks for your contribution!! We just closed this one since as we said before we should not change `html` files directly since those are generated again from GHA.
Thanks again!

**Pull request closed without merging**
