### PR TITLE
(docs) improvements

### PR DESCRIPTION
**Pull request by sacha-l**
* [x] Updates the docs to reflect that the setup script is now part of `cli`
* [x] Fixes the documentation about setting up env variable and executable
* [ ] Adds more commands and examples of real use cases

Relates to #393.

### CODE REVIEW

**Comment by wirednkod** [comment]
This looks great @sacha-l . Thank you so much. Are you intending to fill all 3 in a single PR?

**Comment by sacha-l** [comment]
I think I may do "Adds more commands and examples of real use cases" as a separate one. But either way I'm going to need you or @pepoviola's help on items 2, 3 and 4 in #393. Can you please comment there to advise how to unblock the issues I've listed?

**Review by wirednkod — APPROVED** [review]
Thank you Sacha. Looks good

**Comment by wirednkod** [comment]
#395 addresses 2nd bullet

**Review by wirednkod — APPROVED** [review]
Thank you so much @sacha-l . Looks good to me.

cc @pepoviola

**Pull request closed without merging**
