### PR TITLE
chore: changed raw string zombie role to enum

### PR DESCRIPTION
**Pull request by l0r1s**
Refacto for https://github.com/paritytech/zombienet/issues/901

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]
Looks good! thanks, I think there are a couple of formating issues.

**Review by wirednkod — APPROVED** [review]

**Comment by wirednkod** [comment]
> Looks good! thanks, I think there are a couple of formating issues.

Looks good. I wonder why the PR got to open, since we have the hooks now 🤔

**Comment by l0r1s** [comment]
I added the missing "postinstall" script to make husky install automatic when you run "npm install"

**Comment by l0r1s** [comment]
Fixed following husky doc to avoid running in pipeline

**Pull request merged**
