### PR TITLE
Fix race conditions with getRandomPort by storing previous ports

### PR DESCRIPTION
**Pull request by tmpolaczyk**
I noticed that sometimes when starting a network with many parachains, one of the nodes seems to fail to start, with the following error seen in the zombienet logs repeatedly:

```
Error 	 fetching metrics from: http://127.0.0.1:44539/metrics
```

After inspecting the node logs, it turns out that the prometheus port of one node was being used as the rpc port of another node. Surprisingly, that random port was assigned by zombienet, as you can see in the yaml files:

```
Collator11.yaml
38:      --prometheus-port 44539 --rpc-port 35281 --ws-port 34043 --collator --

Collator02.yaml
38:      --prometheus-port 35579 --rpc-port 44539 --ws-port 45055 --collator --
```

So that error can be avoided by storing the ports returned by the `getRandomPort` function, and ensuring that it doesn't return the same port twice. So that's what is done in this PR, and I have verified it fixes the problem.

### CODE REVIEW

**Comment by wirednkod** [comment]
Thank you @tmpolaczyk . Good catch!

**Comment by tmpolaczyk** [comment]
Fixed the eslint errors.

**Review by pepoviola — APPROVED** [review]
thanks!!

**Comment by pepoviola** [comment]
Merging, thanks!

**Pull request merged**
