### PR TITLE
[WIP] Move CI from Gitlab to GitHub

### PR DESCRIPTION
**Pull request by alvicsam**
cc https://github.com/paritytech/ci_cd/issues/1054

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]

**Comment by pepoviola** [comment]
Hi @alvicsam, is this still _ongoing_?
thx!

**Comment by alvicsam** [comment]
@pepoviola this PR is a template for you to move ci from gitlab to github. I'm still waiting zombienet self-hosted runners.

**Comment by pepoviola** [comment]
@alvicsam / @emamihe smoke tests are now working 🚀, can we merge it?

**Comment by pepoviola** [comment]
@alvicsam / @emamihe I will merge this one and remove `gitlab` in a followup pr.

Thanks!!

**Pull request merged**
