### PR TITLE
Bump nix npmdepshash

### PR DESCRIPTION
**Pull request by rgoulter**
For the Nix stuff added in #772, following #808.

Each time the `javascript/package-lock.json` updates (and it has been updated since the last time flake-modules.nix was updated in #808), someone who likes nix should run something like:

```
nix run nixpkgs#prefetch-npm-deps -- javascript/package-lock.json 2>/dev/null
# update npmDepsHash with this value
```

to update the value of the `npmDepsHash` in the `flake-module.nix`.

cc @dzmitry-lahoda

### CODE REVIEW

**Comment by wirednkod** [comment]
Thank you @rgoulter . I think it will be nice to add inside the [documentation](https://paritytech.github.io/zombienet), (maybe at the [setup page](https://paritytech.github.io/zombienet/cli/setup.html)?) some information about nix, including the info added in this PR. What do you think?

**Comment by rgoulter** [comment]
> I think it will be nice to add inside the [documentation](https://paritytech.github.io/zombienet), (maybe at the [setup page](https://paritytech.github.io/zombienet/cli/setup.html)?) some information about nix,

Right, it would be good to get #775 done.

I think the right place to add it is near the installation documentation. -- a command like `nix run github:paritytech/zombienet` is roughly equivalent to "download the latest build of `zombienet` and run that".

I'll send a PR with some documentation briefly explaining Nix, and a couple of useful ways of using it.

> including the info added in this PR.

Ah, I see that the docs do have a "development" page.
https://paritytech.github.io/zombienet/development.html

Yes, I think it would be useful to add the same details I included in this PR in the "development documentation". Albeit, the prefetch command is already mentioned in `flake-module.nix`.
https://github.com/paritytech/zombienet/blob/d13975e40c0f9933d22ec70939189e14ad45be62/flake-module.nix#L19

**Comment by wirednkod** [comment]
> I'll send a PR with some documentation briefly explaining Nix, and a couple of useful ways of using it.

Thank you so much @rgoulter ! That would be great - and will close #775 as well. Feel free to add it as a "fixes #775" in that PR in order to close once merged

**Review by wirednkod — APPROVED** [review]
Besides the comments concerning Documentation this looks good to me

**Review by pepoviola — APPROVED** [review]

**Pull request merged**
