### PR TITLE
fix: fixed convert issues (missing port, args and escaped name)

### PR DESCRIPTION
**Pull request by l0r1s**
Following this issue #550, only the name was taken from polkadot-launch configuration and with string interpolation for relaychain nodes instead of just using the name as-is.

Here is now the input used and output result: 

## Input:
```json
{
  "relaychain": {
    "bin": "../../../bin/master/polkadot",
    "chain": "kusama-local",
    "nodes": [
      {
        "name": "alice",
        "wsPort": 9900,
        "port": 30444
      },
      {
        "name": "bob",
        "wsPort": 9901,
        "port": 30555
      },
      {
        "name": "charlie",
        "wsPort": 9902,
        "port": 30666
      },
      {
        "name": "dave",
        "wsPort": 9903,
        "port": 30777
      }
    ],
    "genesis": {
      "runtime": {
        "runtime_genesis_config": {
          "configuration": {
            "config": {
              "validation_upgrade_frequency": 1,
              "validation_upgrade_delay": 30
            }
          }
        }
      }
    }
  },
  "parachains": [
    {
      "bin": "../../../bin/polkadot-parachain",
      "chain": "statemine-local",
      "nodes": [
        {
          "wsPort": 9910,
          "port": 31200,
          "name": "alice",
          "flags": [
            "-lxcm-executor=trace",
            "-lxcm=trace",
            "-lxcm::execute_xcm_in_credit=trace",
            "-lxcm::execute_xcm=trace",
            "-lxcm::execute=trace",
            "-lxcm::send_xcm=trace",
            "-lxcm::origin_conversion=trace",
            "-lruntime=debug",
            "-laura=debug",
            "-lcumulus=debug",
            "-lcumulus-collator=debug",
            "-lnacho=debug",
            "--force-authoring",
            "--execution=wasm",
            "--",
            "--execution=wasm"
          ]
        },
        {
          "wsPort": 9911,
          "port": 31201,
          "name": "bob",
          "flags": ["--force-authoring", "--", "--execution=wasm"]
        }
      ]
    },
    {
      "bin": "../../../bin/parachain-collator",
      "chain": "kusama-community-parachain-2000",
      "nodes": [
        {
          "wsPort": 9920,
          "port": 31202,
          "name": "alice",
          "flags": ["--force-authoring", "--", "--execution=wasm"]
        },
        {
          "wsPort": 9921,
          "port": 31203,
          "name": "bob",
          "flags": ["--force-authoring", "--", "--execution=wasm"]
        }
      ]
    }
  ],
  "simpleParachains": [],
  "hrmpChannels": [],
  "types": {},
  "finalization": false
}
```

## Output:
```json
{
  "relaychain": {
    "default_image": "docker.io/paritypr/polkadot-debug:master",
    "default_command": "polkadot",
    "default_args": ["-lparachain=debug"],
    "chain": "kusama-local",
    "nodes": [
      {
        "name": "alice",
        "wsPort": 9900,
        "port": 30444,
        "validator": true,
        "invulnerable": true,
        "balance": 2000000000000
      },
      {
        "name": "bob",
        "wsPort": 9901,
        "port": 30555,
        "validator": true,
        "invulnerable": true,
        "balance": 2000000000000
      },
      {
        "name": "charlie",
        "wsPort": 9902,
        "port": 30666,
        "validator": true,
        "invulnerable": true,
        "balance": 2000000000000
      },
      {
        "name": "dave",
        "wsPort": 9903,
        "port": 30777,
        "validator": true,
        "invulnerable": true,
        "balance": 2000000000000
      }
    ],
    "genesis": {
      "runtime": {
        "runtime_genesis_config": {
          "configuration": {
            "config": {
              "validation_upgrade_frequency": 1,
              "validation_upgrade_delay": 30
            }
          }
        }
      }
    }
  },
  "types": {},
  "hrmp_channels": [],
  "parachains": [
    {
      "collators": [
        {
          "wsPort": 9910,
          "port": 31200,
          "name": "alice",
          "flags": [
            "-lxcm-executor=trace",
            "-lxcm=trace",
            "-lxcm::execute_xcm_in_credit=trace",
            "-lxcm::execute_xcm=trace",
            "-lxcm::execute=trace",
            "-lxcm::send_xcm=trace",
            "-lxcm::origin_conversion=trace",
            "-lruntime=debug",
            "-laura=debug",
            "-lcumulus=debug",
            "-lcumulus-collator=debug",
            "-lnacho=debug",
            "--force-authoring",
            "--execution=wasm",
            "--",
            "--execution=wasm"
          ],
          "command": "adder-collator",
          "validator": true,
          "invulnerable": true,
          "balance": 2000000000000
        },
        {
          "wsPort": 9911,
          "port": 31201,
          "name": "bob",
          "flags": ["--force-authoring", "--", "--execution=wasm"],
          "command": "adder-collator",
          "validator": true,
          "invulnerable": true,
          "balance": 2000000000000
        }
      ]
    },
    {
      "collators": [
        {
          "wsPort": 9920,
          "port": 31202,
          "name": "alice",
          "flags": ["--force-authoring", "--", "--execution=wasm"],
          "command": "adder-collator",
          "validator": true,
          "invulnerable": true,
          "balance": 2000000000000
        },
        {
          "wsPort": 9921,
          "port": 31203,
          "name": "bob",
          "flags": ["--force-authoring", "--", "--execution=wasm"],
          "command": "adder-collator",
          "validator": true,
          "invulnerable": true,
          "balance": 2000000000000
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Comment by wirednkod** [comment]
I am not sure I follow you in this one.
There are more issues that needs to be covered, following [this comment](https://github.com/paritytech/zombienet/issues/550#issuecomment-1298790536). At the moment the conversion from polkadot-launch is extremely basic. In order to be able to finalize it, we need some sample code and examples of a working polkadot-launch project. 

I have some of those from an existing project, and is in my todo-list based on priority, and I wanna go through those in the upcoming days

**Comment by l0r1s** [comment]
Alright, I keep this open then and you can update me if you have any projet config I can test against

**Comment by wirednkod** [comment]
> Alright, I keep this open then and you can update me if you have any projet config I can test against

There are a lot of misalignment for what I have noticed. We can coordinate on this offline and you can add your findings here afterwards.

**Review by pepoviola — APPROVED** [review]

**Comment by pepoviola** [comment]
Hi @l0r1s, can you resolve the conflicts and merge this one 👍 
Thanks!!

**Comment by l0r1s** [comment]
@pepoviola I will just close this, already merge here: https://github.com/paritytech/zombienet/pull/921

**Pull request closed without merging**
