### PR TITLE
Add oak decorators

### PR DESCRIPTION
**Pull request by nvengal**

### CODE REVIEW

**Review by wirednkod — APPROVED** [review]
lgtm

**Comment by pepoviola** [comment]
Hi @nvengal looks good, thanks for your contribution. Can you run `npm run lint:write` and push the changes since the `ci` fails because of the linter. Also, there is any official image we can use to add a test in our `ci` for Oak?

Again, thanks for your contribution!!

**Comment by nvengal** [comment]
Thanks for the quick review!

@pepoviola linter is run. This is the official image for our canary network: https://hub.docker.com/r/oaknetwork/turing/tags (mainnet not launched yet)

**Review by pepoviola — APPROVED** [review]

**Comment by pepoviola** [comment]
> Thanks for the quick review!
> 
> @pepoviola linter is run. This is the official image for our canary network: https://hub.docker.com/r/oaknetwork/turing/tags (mainnet not launched yet) Should be run with `--chain "turing-dev"` for development/testing.

Great, thanks!!! follow up issue https://github.com/paritytech/zombienet/issues/579.

Merging now. Thanks again for your contribution.

**Pull request merged**
