### PR TITLE
Fix Moonbase collator balance

### PR DESCRIPTION
**Pull request by imstar15**
Fix the error that occurs when Moonbase starts:

```
Thread 'main' panicked at 'Account does not have enough balance to bond as a candidate.
```

### CODE REVIEW

**Review by pepoviola — APPROVED** [review]

**Review by wirednkod — APPROVED** [review]

**Comment by imstar15** [comment]
Hi @pepoviola 
continuous-integration/gitlab-paras failed. How should I fix it?

**Comment by chrisli30** [comment]
Hi @wirednkod, this is Chris from OAK Network. There are three tasks failed from the check automation of this PR, but we don’t have permission to view those.

continuous-integration/gitlab-paras — {"build_allow_failure":true}
continuous-integration/gitlab-publish-docker-pr — {"build_allow_failure":false}
continuous-integration/gitlab-publish-test — {"build_allow_failure":false}

How could we help resolve those issues?

**Comment by pepoviola** [comment]
> Hi @wirednkod, this is Chris Li from OAK Network. There are three tasks failed from the check automation of this PR, but we don’t have permission to view those.
> 
> continuous-integration/gitlab-paras — {"build_allow_failure":true} continuous-integration/gitlab-publish-docker-pr — {"build_allow_failure":false} continuous-integration/gitlab-publish-test — {"build_allow_failure":false}
> 
> How could we help resolve those issues?

Hi @chrisli30, I'm re-running our pipeline now.
Thanks!!

**Comment by pepoviola** [comment]
ci is failing with this error now
```
Thread 'main' panicked at 'duplicate balances in genesis.', /home/gh-actions/.cargo/git/checkouts/substrate-189071a041b0d328/c674000/frame/balances/src/lib.rs:588
```

I will check it locally.

**Comment by chrisli30** [comment]
> 

Great, thanks for the help Javier!

**Comment by pepoviola** [comment]
Hi @chrisli30, can you update your branch merging master. I think the `dup` issue should be fixed now.
Thanks!

**Comment by chrisli30** [comment]
@pepoviola Thank you for facilitating this PR!

I have rerun the latest code of zombienet and comfirm that this PR fixes the below error with Moonbeam [runtime-2403](https://github.com/moonbeam-foundation/moonbeam/releases/tag/runtime-2403)
`Thread 'main' panicked at 'Account does not have enough balance to bond as a candidate.', /Users/mikasa/Code/moonbeam/pallets/parachain-staking/src/lib.rs:684`

**Comment by pepoviola** [comment]
Awesome! Thanks for your feedback and contribution 🙌.
I will draft a new release tomorrow.
Thx!

**Pull request merged**
